### ISSUE TITLE
`TypeError: performance.mark is not a function` on node@16

### ISSUE THREAD

**Issue by msluther** [sinonjs/nise#193]
There was an issue with `@sinonjs/fake-timers` here: https://github.com/sinonjs/fake-timers/issues/394

That was fixed and published in `sinon@13`. However, even with `sinon@13` I am still hitting this issue due to the `nise` library consuming an older version of fake-timers.

```sh-output
$ npm ls @sinonjs/fake-timers
my-library@0.2.0 /Users/me/my-library
└─┬ sinon@13.0.0
  ├── @sinonjs/fake-timers@9.0.0
  └─┬ nise@5.1.0
    └── @sinonjs/fake-timers@7.1.2
```

Can we update the dependency here and publish a new version (along with a publish consuming that from the root `sinon` library)?

**Comment by fatso83** [comment]
Ooooh, good catch. But why is nise importing fake-timers? 🤔

**Comment by msluther** [comment]
I grabbed a stack trace while I was in there:

```
    at Object.<anonymous> (/Users/me/my-library/node_modules/nise/node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:2:36)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/me/my-library/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/me/my-library/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/me/my-library/node_modules/nise/lib/fake-server/fake-server-with-clock.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/me/my-library/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/me/my-library/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/me/my-library/node_modules/nise/lib/index.js:5:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/me/my-library/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/me/my-library/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/me/my-library/node_modules/sinon/lib/sinon/sandbox.js:16:18)
...
```
